# Generated by Django 5.0.1 on 2026-01-24 06:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, help_text='Fecha única del reporte', unique=True, verbose_name='fecha del reporte')),
                ('base_inicial', models.DecimalField(decimal_places=2, help_text='Base en efectivo al inicio del día', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='base inicial')),
                ('venta_total', models.DecimalField(decimal_places=2, help_text='Total de ventas del día', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='venta total')),
                ('total_gastos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total de gastos del día (calculado automáticamente)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total de gastos')),
                ('entrega', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Dinero entregado/retirado del día', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='entrega')),
                ('base_siguiente', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base calculada para el día siguiente', max_digits=12, verbose_name='base del día siguiente')),
                ('observacion', models.TextField(blank=True, help_text='Observaciones o notas adicionales del día', verbose_name='observación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('usuario_creacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_creados', to=settings.AUTH_USER_MODEL, verbose_name='usuario que creó el reporte')),
            ],
            options={
                'verbose_name': 'reporte diario',
                'verbose_name_plural': 'reportes diarios',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='VentaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(help_text='Cantidad de unidades vendidas', validators=[django.core.validators.MinValueValidator(1)], verbose_name='cantidad vendida')),
                ('precio_unitario_momento', models.DecimalField(decimal_places=2, help_text='Precio del producto al momento de registrar la venta', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='precio unitario en el momento de la venta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='productos.producto', verbose_name='producto')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_productos', to='reportes.reportediario', verbose_name='reporte diario')),
            ],
            options={
                'verbose_name': 'venta de producto',
                'verbose_name_plural': 'ventas de productos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddIndex(
            model_name='reportediario',
            index=models.Index(fields=['-fecha'], name='reportes_re_fecha_d1d1fa_idx'),
        ),
        migrations.AddIndex(
            model_name='reportediario',
            index=models.Index(fields=['fecha_creacion'], name='reportes_re_fecha_c_fba290_idx'),
        ),
        migrations.AddIndex(
            model_name='ventaproducto',
            index=models.Index(fields=['reporte', 'producto'], name='reportes_ve_reporte_299a32_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ventaproducto',
            unique_together={('reporte', 'producto')},
        ),
    ]
