# Generated by Django 5.0.1 on 2026-01-24 06:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre único del producto', max_length=200, unique=True, verbose_name='nombre del producto')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio de venta por unidad en pesos colombianos', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='precio unitario')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el producto está activo para ventas', verbose_name='activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre'], name='productos_p_nombre_456643_idx'), models.Index(fields=['activo'], name='productos_p_activo_31f808_idx')],
            },
        ),
    ]
