# Generated by Django 5.0.1 on 2026-04-14 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Indica si el producto ha sido eliminado (soft delete)', verbose_name='eliminado'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['deleted'], name='productos_p_deleted_7d0711_idx'),
        ),
    ]
