# Generated by Django 5.0.1 on 2026-01-24 06:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre único de la categoría', max_length=100, unique=True, verbose_name='nombre de la categoría')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional de la categoría', verbose_name='descripción')),
                ('activa', models.BooleanField(default=True, help_text='Indica si la categoría está activa', verbose_name='activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'categoría de gasto',
                'verbose_name_plural': 'categorías de gastos',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre'], name='gastos_cate_nombre_9d4be8_idx'), models.Index(fields=['activa'], name='gastos_cate_activa_4be238_idx')],
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Descripción breve del gasto', max_length=200, verbose_name='descripción')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor del gasto en pesos colombianos', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='valor')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('categoria', models.ForeignKey(blank=True, help_text='Categoría del gasto (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='gastos.categoriagasto', verbose_name='categoría')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='reportes.reportediario', verbose_name='reporte diario')),
            ],
            options={
                'verbose_name': 'gasto',
                'verbose_name_plural': 'gastos',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['reporte', 'categoria'], name='gastos_gast_reporte_4a91c7_idx'), models.Index(fields=['-fecha_creacion'], name='gastos_gast_fecha_c_74124b_idx')],
            },
        ),
    ]
