# Generated by Django 5.0.1 on 2026-04-09 10:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoAutomatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Descripción del gasto automático', max_length=200, verbose_name='descripción')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor predefinido para este gasto', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='valor predefinido')),
                ('activo', models.BooleanField(default=True, help_text='Indica si está disponible para usar', verbose_name='activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_automaticos', to='gastos.categoriagasto', verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'gasto automático',
                'verbose_name_plural': 'gastos automáticos',
                'ordering': ['categoria', 'descripcion'],
                'indexes': [models.Index(fields=['categoria', 'activo'], name='gastos_gast_categor_2388e8_idx')],
            },
        ),
        migrations.CreateModel(
            name='GastoDeducible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('transferencia', 'Transferencia'), ('ahorro', 'Ahorro'), ('ingreso', 'Ingreso')], default='ingreso', help_text='Clasificación del deducible', max_length=20, verbose_name='tipo de deducible')),
                ('descripcion', models.TextField(blank=True, help_text='Explicación de por qué esta categoría es deducible', verbose_name='descripción')),
                ('activo', models.BooleanField(default=True, help_text='Si está activo, se restará de gastos', verbose_name='activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('categoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deducible', to='gastos.categoriagasto', verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'gasto deducible',
                'verbose_name_plural': 'gastos deducibles',
                'ordering': ['categoria'],
                'indexes': [models.Index(fields=['activo', 'tipo'], name='gastos_gast_activo_2c618b_idx')],
            },
        ),
    ]
