# Generated by Django 5.0.1 on 2026-04-14 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_gastoautomatico_gastodeducible'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriagasto',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Indica si la categoría ha sido eliminada (soft delete)', verbose_name='eliminada'),
        ),
        migrations.AddField(
            model_name='gastoautomatico',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Indica si ha sido eliminado (soft delete)', verbose_name='eliminado'),
        ),
        migrations.AddField(
            model_name='gastodeducible',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Indica si ha sido eliminado (soft delete)', verbose_name='eliminado'),
        ),
        migrations.AddIndex(
            model_name='categoriagasto',
            index=models.Index(fields=['deleted'], name='gastos_cate_deleted_2d28c4_idx'),
        ),
        migrations.AddIndex(
            model_name='gastoautomatico',
            index=models.Index(fields=['deleted'], name='gastos_gast_deleted_ee9f68_idx'),
        ),
        migrations.AddIndex(
            model_name='gastodeducible',
            index=models.Index(fields=['deleted'], name='gastos_gast_deleted_bc8003_idx'),
        ),
    ]
